
services:
  postgres:
    image: postgres:15
    container_name: postgres-sui-indexer
    environment:
      POSTGRES_USER: admin           
      POSTGRES_PASSWORD: password    
      POSTGRES_DB: sui_indexer
    ports:
      - "5432:5432"
    networks:
      - sui-local-network

  local-sui-platform:
    build: 
      dockerfile: Dockerfile
      target: fresh_start_with_indexer
      # TODO: Pass args in for configurable local username and password
      # args:
      #   INDEXER_DB_URL: "postgres-sui-indexer"
    container_name: local-sui-platform
    depends_on:
      - postgres
      - deepbook-indexer-mock
    ports:
      - "9000:9000"
    networks:
      - sui-local-network

  deepbook-indexer-mock:
    image: wiremock/wiremock:3.11.0-1
    container_name: deepbook-indexer
    volumes:
      - ./environments/$ENVIRONMENT/wiremock-config:/home/wiremock
    ports:
      - 8080:8080
    networks:
      - sui-local-network
    command: [ "--global-response-templating" ]
        
networks:
  sui-local-network:
    driver: bridge
