[package]
name = "rust_client_sui"
version = "0.1.0"
edition = "2021"

[dependencies]
sui_sdk = { git = "https://github.com/mystenlabs/sui", package = "sui-sdk"}
sui-sdk-types = "0.0.2"
tokio = { version = "1.43.0", features = ["full"] }
anyhow = "1.0.95"
